### ISSUE TITLE
change-scheduler-scope

### ISSUE THREAD

**Issue by sssylvester** [geopm/geopm#14]
Change the use of the SampleScheduler to account for the overhead
introduced by ProfileThread interface (tprof), not just the
overhead from the Profile interface.

**Comment by cmcantalupo** [comment]
The SampleScheduler is a rate limiter used in the ProfileTable for updates to progress() (not enter or exit).  Progress is implemented in a different way now for the tprof table than when this bug was opened.  The new implementation is lockless and very fast.  We do not need to rate limit the tprof_post calls with the new implementation.
