### ISSUE TITLE
Support for overriding settings from environment with values from disk

### ISSUE THREAD

**Issue by dianarg** [geopm/geopm#192]

**Comment by cmcantalupo** [comment]
I'm not sure why this issue was closed, but I'd like to reopen it.   The following would be useful in the context of enabling system administrator control of some parameters for geopm:

Two optional configuration files can be added.  Suggested location:

/var/lib/geopm/environment-override.json
/var/lib/geopm/environment-default.json

An example file would be contain the following text:
{
    "GEOPM_AGENT": "power_balancer"
    "GEOPM_POLICY": "/var/lib/geopm/policy.json"
}

If this was the environment-override.json, every contronroller run on that compute node would execute the power balancer agent with the policy file specified.  This could be used to enforce a power cap on the system.

**Comment by tpatki** [comment]
As per our discussion, here are my thoughts and what I think we should commit to for the first cut. 
[SLURM.docx](https://github.com/geopm/geopm/files/3091371/SLURM.docx)

**Comment by tpatki** [comment]
Yes. This is what we're intending to commit for June, mostly capturing discussions with Chris and adding clarity so we don't (1) start with too many broad assumptions, and (2) overcommit and not be able to deliver the milestone on time.
