### ISSUE TITLE
POSIXSignalTest.sig_queue_EPERM test failing

### ISSUE THREAD

**Issue by Alessandro-Barbieri** [geopm/geopm#2382]
**Describe the bug**
I tried to run the tests of geopmd and I expected them to pass instead one failed

**GEOPM version**
2.0.0+rc1

**Expected behavior**
All tests passing

**Actual behavior**
1 test is failing

**Error messages produced**
FAIL: test/gtest_links/POSIXSignalTest.sig_queue_EPERM
Was debug messaging was enabled at build time? No

**Additional context**

see https://bugs.gentoo.org/852260
log https://852260.bugs.gentoo.org/attachment.cgi?id=785567

**Comment by bgeltz** [comment]
Thanks for the bug report @Alessandro-Barbieri.

Would you please provide the contents of the log file for the failing test?  It is not available from the build.log in the linked bug reports.

The path to the log file contents from a passing run are as follows:
```
$ cat service/test/gtest_links/POSIXSignalTest.sig_queue_EPERM.log
Note: Google Test filter = POSIXSignalTest.sig_queue_EPERM
[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from POSIXSignalTest
[ RUN      ] POSIXSignalTest.sig_queue_EPERM
[       OK ] POSIXSignalTest.sig_queue_EPERM (0 ms)
[----------] 1 test from POSIXSignalTest (0 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test suite ran. (0 ms total)
[  PASSED  ] 1 test.
```

Based on the paths in the build.log from the linked bug reports, that path appears to be:
```
/var/tmp/portage/sys-power/geopmd-2.0.0_rc1/work/geopm-2.0.0-rc1/service/test/gtest_links/POSIXSignalTest.sig_queue_EPERM.log
```

**Comment by Alessandro-Barbieri** [comment]
Testing on my machine
```
cat /var/tmp/portage/sys-power/geopmd-2.0.0_rc1/work/geopm-2.0.0-rc1/service/test/gtest_links/POSIXSignalTest.sig_queue_EPERM.log
Note: Google Test filter = POSIXSignalTest.sig_queue_EPERM
[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from POSIXSignalTest
[ RUN      ] POSIXSignalTest.sig_queue_EPERM
test/POSIXSignalTest.cpp:205: Failure
Expected to throw, but succeeded.
[  FAILED  ] POSIXSignalTest.sig_queue_EPERM (0 ms)
[----------] 1 test from POSIXSignalTest (0 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test suite ran. (0 ms total)
[  PASSED  ] 0 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] POSIXSignalTest.sig_queue_EPERM
```

**Comment by cmcantalupo** [comment]
Hi @Alessandro-Barbieri,

Thanks again for the feedback.  I believe that you are running this test as the "root" user.  The test that is failing is not valid when run by the "root" user.  The PR #2387 modifies the test to be skipped at runtime in this case.  Please let us know if this patch may be applied to the build to resolve your issue:

593caaa68a405e412506138a5ab2987c56d2ab06

The change will be included in the next release candidate.

**Comment by cmcantalupo** [comment]
Looks like this patch does not solve the problem:

https://github.com/geopm/geopm/pull/2387#issuecomment-1163787870

@Alessandro-Barbieri

Sorry I didn't notice the reply sooner.  Reopening issue.  Thanks for the feedback!

**Comment by cmcantalupo** [comment]
It seems that we will have to check for `CAP_KILL` in `procfs` rather than checking for user `root` with `geteuid()`.  We have similar python code to check for `CAP_SYSADMIN` here:

https://github.com/geopm/geopm/blob/dev/service/geopmdpy/service.py#L838-L848

We will have to do something similar in C++ to check for `CAP_KILL` for the test process and skip the test if the capability is present.

**Comment by Krebrov001** [comment]
The error is occuring because the `portage` package manager creates it's own user, which is not the `root` or `sudo` user, but contains elevated permissions.

That exception is occurring in one of our tests, which checks that the current process doesn't have permissions to send a signal to just *any arbitrary* user on the system. The current process is running inside of it's own user, which has some certain permissions. The current test assumes that the user of the current process is a "normal user", meaning that it doesn't have any super special extra permissions. That may not actually be the case.

Some apps, such as package managers, add new users, their own users, in order to do their job under elevated permissions, such as installing new applications and modifying config files. These special purpose users often have elevated permissions, but are not actually the `root` user, so checking the **uid** doesn't work for them. We need to update the tests to consider the specific capabilities of the user of the process, instead of assuming that *all* users other than the `root` user have "normal" permissions (this is not the case). We will do that by querying the  `procfs`.

**Comment by Krebrov001** [comment]
@Alessandro-Barbieri  I have written a patch for this issue. Please download the revision of the code in the `dev` branch, the commit hash `2e958f3`. Please test, if the new code solves your issue, please let us know.

**Comment by Krebrov001** [comment]
@Alessandro-Barbieri  Please check to see if the latest geopm release candidate fixes your issue.
