### ISSUE TITLE
Update Python scripts to support power capping experiments

### ISSUE THREAD

**Issue by dianarg** [geopm/geopm#299]
We need to add plots for node characterization to the plotter.  Also, we need functions in analysis or plotter to display the achieved power from the power_consumption integration test and the plots comparing the governor and the balancer.

**Comment by bgeltz** [comment]
This is WIP.  Diana started a script based on the integration tests that will print power statistics for the sockets and DRAM as calculated from the trace files.  I've been extending it a bit to print a data summary (rather than just the individual per-node data), as well as per region power data.

These are just tables for the moment.  No plots are being generated just yet.
