### ISSUE TITLE
Update GEOPM on production systems to 1.0.0 release

### ISSUE THREAD

**Issue by dianarg** [geopm/geopm#583]
Also update OpenHPC

**Comment by cmcantalupo** [comment]
Update has been installed on Theta.

Pull request has been made to OpenHPC:  https://github.com/openhpc/ohpc/pull/986

**Comment by maiterth** [comment]
Yes, still a few things to work out before spack agrees to merge, but it's on the way and a working pull request in my https://github.com/maiterth/spack/tree/package/geopm 

Using spack to build from dev and master still needs some adjustments due to spacks implementation of using autotools and git repositories and our requirements regarding generated VERSION file. 
The branch for normal release versions works and geopm@1.0.0 works fine.
