### ISSUE TITLE
Write prerequisites section for admin tutorial

### ISSUE THREAD

**Issue by cmcantalupo** [geopm/geopm#886]
> estimate 2

Most documentation is covered top level README, this work is primarily about writing the test script.

Script below may be useful.
https://github.com/geopm/endeavor-tutorial/blob/master/test-msr-safe.sh

Example RAPL script in geopm/story-806

Parent story #806

Done Criteria:
1. Verify documentation and elaborate on pointers in this doc.
2. Write the script to configure as much as possible in the system.
3. Write the test script to verify the system is configured properly.

**Comment by bgeltz** [comment]
Filed #907 as a follow-on task.

**Comment by bgeltz** [comment]
Re: Done Criteria, #2:
Since most of the things that are examined by the test script are not easily configurable by a script, and that they could touch critical bits of the OS image (e.g. the kernel command line) this line item was not attempted.  Instead pointers to the existing documentation and clear error messages when a misconfiguration is detected are provided.
